function b = nlinkpend_Euler_b(in1,in2,in3,g,in5,in6,in7)
%NLINKPEND_EULER_B
%    B = NLINKPEND_EULER_B(IN1,IN2,IN3,G,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-Dec-2018 00:19:03

d1 = in3(:,1);
d2 = in3(:,2);
d3 = in3(:,3);
l1 = in2(:,1);
l2 = in2(:,2);
m1 = in5(:,1);
m2 = in5(:,2);
m3 = in5(:,3);
th1 = in7(:,1);
th2 = in7(:,2);
th3 = in7(:,3);
thd1 = in6(:,1);
thd2 = in6(:,2);
thd3 = in6(:,3);
t2 = sin(th1);
t3 = sin(th2);
t4 = th1-th2;
t5 = sin(t4);
t6 = thd1.^2;
t7 = th1-th3;
t8 = sin(t7);
t9 = thd2.^2;
t10 = thd3.^2;
t11 = th2-th3;
t12 = sin(t11);
t13 = d2.*g.*m2.*t3;
t14 = sin(th3);
t15 = d3.*g.*m3.*t14;
t16 = g.*l2.*m3.*t3;
t17 = d3.*l2.*m3.*t10.*t12;
b = [t13+t15+t16+t17+d1.*g.*m1.*t2+g.*l1.*m2.*t2+g.*l1.*m3.*t2-d2.*l1.*m2.*t5.*t6+d2.*l1.*m2.*t5.*t9-d3.*l1.*m3.*t6.*t8+d3.*l1.*m3.*t8.*t10-d3.*l2.*m3.*t9.*t12-l1.*l2.*m3.*t5.*t6+l1.*l2.*m3.*t5.*t9;t13+t15+t16+t17-d2.*l1.*m2.*t5.*t6-d3.*l1.*m3.*t6.*t8-d3.*l2.*m3.*t9.*t12-l1.*l2.*m3.*t5.*t6;-d3.*m3.*(-g.*t14+l1.*t6.*t8+l2.*t9.*t12)];
