function b = nlinkpend_DAE_b(in1,in2,in3,g,in5,in6,in7)
%NLINKPEND_DAE_B
%    B = NLINKPEND_DAE_B(IN1,IN2,IN3,G,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    17-Jul-2019 19:26:51

d1 = in3(:,1);
d2 = in3(:,2);
d3 = in3(:,3);
d4 = in3(:,4);
d5 = in3(:,5);
d6 = in3(:,6);
l1 = in2(:,1);
l2 = in2(:,2);
l3 = in2(:,3);
l4 = in2(:,4);
l5 = in2(:,5);
m1 = in5(:,1);
m2 = in5(:,2);
m3 = in5(:,3);
m4 = in5(:,4);
m5 = in5(:,5);
m6 = in5(:,6);
th1 = in7(:,1);
th2 = in7(:,2);
th3 = in7(:,3);
th4 = in7(:,4);
th5 = in7(:,5);
th6 = in7(:,6);
thd1 = in6(:,1);
thd2 = in6(:,2);
thd3 = in6(:,3);
thd4 = in6(:,4);
thd5 = in6(:,5);
thd6 = in6(:,6);
t2 = thd1.^2;
t3 = cos(th1);
t4 = thd2.^2;
t5 = cos(th2);
t6 = thd3.^2;
t7 = cos(th3);
t8 = thd4.^2;
t9 = cos(th4);
t10 = thd5.^2;
t11 = cos(th5);
t12 = sin(th1);
t13 = sin(th2);
t14 = sin(th3);
t15 = sin(th4);
t16 = sin(th5);
t17 = thd6.^2;
b = [-g.*m1;-g.*m2;-g.*m3;-g.*m4;-g.*m5;-g.*m6;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;-d1.*t2.*t3;d1.*t2.*t3-d2.*t4.*t5-l1.*t2.*t3;d2.*t4.*t5-d3.*t6.*t7-l2.*t4.*t5;d3.*t6.*t7-d4.*t8.*t9-l3.*t6.*t7;d4.*t8.*t9-d5.*t10.*t11-l4.*t8.*t9;-d6.*t17.*cos(th6)+d5.*t10.*t11-l5.*t10.*t11;-d1.*t2.*t12;d1.*t2.*t12-d2.*t4.*t13-l1.*t2.*t12;d2.*t4.*t13-d3.*t6.*t14-l2.*t4.*t13;d3.*t6.*t14-d4.*t8.*t15-l3.*t6.*t14;d4.*t8.*t15-d5.*t10.*t16-l4.*t8.*t15;-d6.*t17.*sin(th6)+d5.*t10.*t16-l5.*t10.*t16];
