function M = nlinkpend_Euler_M(in1,in2,in3,g,in5,in6,in7)
%NLINKPEND_EULER_M
%    M = NLINKPEND_EULER_M(IN1,IN2,IN3,G,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-Dec-2018 00:19:02

I1 = in1(:,1);
I2 = in1(:,2);
I3 = in1(:,3);
d1 = in3(:,1);
d2 = in3(:,2);
d3 = in3(:,3);
l1 = in2(:,1);
l2 = in2(:,2);
m1 = in5(:,1);
m2 = in5(:,2);
m3 = in5(:,3);
th1 = in7(:,1);
th2 = in7(:,2);
th3 = in7(:,3);
t2 = sin(th1);
t3 = cos(th1);
t4 = cos(th2);
t5 = l1.*t3;
t6 = sin(th2);
t7 = l1.*t2;
t8 = d1.^2;
t9 = sin(th3);
t10 = d3.*t9;
t11 = l2.*t6;
t12 = t7+t10+t11;
t13 = cos(th3);
t14 = d3.*t13;
t15 = l2.*t4;
t16 = t5+t14+t15;
t17 = d2.*t4;
t18 = t5+t17;
t19 = d2.*t6;
t20 = t7+t19;
t21 = t14+t15;
t22 = t10+t11;
t23 = d2.^2;
t24 = d3.^2;
M = reshape([-I1-m1.*(t2.^2.*t8+t3.^2.*t8)-m3.*(l1.*t2.*t12+l1.*t3.*t16)-m2.*(l1.*t3.*t18+l1.*t2.*t20),-m2.*(d2.*l1.*t3.*t4+d2.*l1.*t2.*t6)-m3.*(l1.*t2.*t22+l1.*t3.*t21),-m3.*(d3.*l1.*t2.*t9+d3.*l1.*t3.*t13),-I2-m2.*(d2.*t4.*t18+d2.*t6.*t20)-m3.*(l2.*t6.*t12+l2.*t4.*t16),-I2-m2.*(t4.^2.*t23+t6.^2.*t23)-m3.*(l2.*t4.*t21+l2.*t6.*t22),-m3.*(d3.*l2.*t6.*t9+d3.*l2.*t4.*t13),-I3-m3.*(d3.*t9.*t12+d3.*t13.*t16),-I3-m3.*(d3.*t9.*t22+d3.*t13.*t21),-I3-m3.*(t9.^2.*t24+t13.^2.*t24)],[3,3]);
